Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  #config.vm.network "forwarded_port", guest: 8080, host: 8080   # For Spring web app
  #config.vm.network "forwarded_port", guest: 9090, host: 9090   # For chat app server
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "provision.sh"
end
