Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Define the App VM
  config.vm.define "app" do |app_vm|
    app_vm.vm.hostname = "app"
    app_vm.vm.network "private_network", ip: "192.168.56.12"

    app_vm.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
      ansible.inventory_path = "../ansible/inventory.ini"
      ansible.limit = "app"
    end
  end

  # Optional: Uncomment to define a DB VM
  # config.vm.define "db" do |db_vm|
  #   db_vm.vm.hostname = "db"
  #   db_vm.vm.network "private_network", ip: "192.168.56.13"
  #
  #   db_vm.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "../ansible/site.yml"
  #     ansible.inventory_path = "../ansible/inventory.ini"
  #     ansible.limit = "db"
  #   end
  # end
end
